name: kairos_mobile_app
description: A symbiotic mobile companion for K.A.I.R.O.S.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Theming
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1

  # State Management & Services
  provider: ^6.1.1 
  http: ^1.2.0 
  
  # Utilities
  path_provider: ^2.1.3
  file_picker: ^10.3.1
  open_filex: ^4.3.4
  url_launcher: ^6.2.6
  collection: ^1.17.2
  syncfusion_flutter_pdfviewer: ^30.2.4

  # Symbiotic Link & Background
  flutter_blue_plus: ^1.31.14
  web_socket_channel: ^3.0.3
  flutter_background_service: ^5.0.1
  flutter_local_notifications: ^19.4.0
  notification_listener_service: ^0.3.4
  
  # Native Integrations
  # spotify_sdk: ^3.0.2
  wifi_iot: ^0.3.19+2
  permission_handler: ^12.0.1

  udp: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true