# kairos_mobile_app/pubspec.yaml
name: kairos_mobile_app
description: A symbiotic mobile companion for K.A.I.R.O.S.
# The following line prevents a project from being published to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Ensure this matches your Flutter SDK's Dart version range

dependencies:
  flutter:
    sdk: flutter
  
  # Theming and UI enhancements
  cupertino_icons: ^1.0.6
  
  # For making HTTP requests to your FastAPI server
  http: ^1.2.0 
  
  # State management (lightweight and flexible)
  provider: ^6.1.1 

  # For shared clipboard functionality (we'll primarily use the native platform services via method channels if this doesn't fit, but start here)
  # clipboard_watcher: ^0.1.0 # This package might not be actively maintained or might have permission issues. Let's rely on native clipboard methods first.
  
  # For file operations (reading, writing, temp files)
  path_provider: ^2.1.3 # To get common directories like temp or app documents
  file_picker: ^8.0.0+1 # For selecting files (if we want to send files from phone to PC manually)

  # For opening various file types (PDFs, images)
  open_filex: ^4.3.4 # To open downloaded files with external apps

  # For building aesthetic UIs (optional, but good for "insane" UI)
  flutter_animate: ^4.5.0 # For easy, performant animations
  google_fonts: ^6.2.1 # For custom fonts
  flutter_svg: ^2.0.10+1 # For scalable vector graphics icons
  
  # For PDF Viewer on mobile
  # We'll use a more direct approach initially for PDF viewing or suggest a robust package like 'syncfusion_flutter_pdfviewer'
  # if 'open_filex' isn't sufficient for in-app viewing or specific page navigation.
  # Let's keep it simple with open_filex first, as it directly opens with the system's default PDF viewer.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # For fonts:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic